source 'https://rubygems.org'

gem 'daru', github: 'v0dro/daru'
gem 'dbd-sqlite3'
gem 'dbd-mysql'
gem 'dbi'
gem 'iruby'
gem 'mysql'
gem 'nyaplot'
gem 'rake'
gem 'rbczmq'
gem 'rubyzip'
gem 'sequel'
gem 'sqlite3'
gem 'statsample'
